### ISSUE TITLE
Eliminate uses of deprecated CONSTANTS

### ISSUE THREAD

**Issue by leafpetersen** [google/dart-sync-socket#26]
This package still uses deprecated Dart 1 SCREAMING CAPS CONSTANTS. These will be removed shortly in Dart 2. This rewriting tool can be used to automatically migrate code in most cases: https://github.com/dart-lang/dart2_fix .

**Comment by DrMarcII** [comment]
AFAIK, this code doesn't work in Dart 2 (and is definitely no longer needed in Dart 2 as support synchronous network communication has been added to the standard APIs),
